Update main_workflow.yaml

diff --git a/.github/workflows/main_workflow.yaml b/.github/workflows/main_workflow.yaml
--- a/.github/workflows/main_workflow.yaml
+++ b/.github/workflows/main_workflow.yaml
@@ -21,9 +21,23 @@ jobs:
           ref: ${{ github.ref }}
           token: ${{ github.token }}
           workflow: ${{ matrix.workflow }}.yaml
-
-      - name: Check for failures
-        if: ${{ failure() }}
+          
+  restart_when_failed:
+    name: Restarts the scheduled run when it failed
+    runs-on: ubuntu-latest
+    if: github.event_name == 'schedule' && failure()
+    needs: [parallel-workflows]
+    steps:
+      - name: Retry the workflow
         run: |
-          echo "One of the workflows failed. Restarting all workflows."
-          exit 1
+          curl -i \
+          -X POST \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/ArkoProvo531/upload-artifact/actions/workflows/upload_download_arti.yaml/dispatches \
+          -d '{"ref": "${{ github.ref }}" }'           
+
+   #   - name: Check for failures
+   #     if: ${{ failure() }}
+   ##     run: |
+    #      echo "One of the workflows failed. Restarting all workflows."
+    #      exit 1
