Update workflow-C.yaml

diff --git a/.github/workflows/workflow-C.yaml b/.github/workflows/workflow-C.yaml
--- a/.github/workflows/workflow-C.yaml
+++ b/.github/workflows/workflow-C.yaml
@@ -11,4 +11,5 @@ jobs:
      #   uses: actions/checkout@v2
       - name: Run workflow statement
         run: |
-          echo "This is an example of workflow C"
+          echo "This is an example of workflow C failure"
+          exit 1
