Update workflow-B.yaml

diff --git a/.github/workflows/workflow-B.yaml b/.github/workflows/workflow-B.yaml
--- a/.github/workflows/workflow-B.yaml
+++ b/.github/workflows/workflow-B.yaml
@@ -11,5 +11,6 @@ jobs:
      #   uses: actions/checkout@v2
       - name: Run workflow statement
         run: |
-          echo "This is an example of workflow B "
+          echo "This is an example of workflow B failure "
+          exit 1
           
